apiVersion: v1
kind: ConfigMap
metadata:
  name: envread-settings
data:
  app.config.json: |-
    {
      "name": "envapp",
      "version": "1.0.0",
      "environment": "Develop",
      "basehref": "envapp",
      "backgroundColor": "blue"
    }
---
apiVersion: v1
kind: Service
metadata:
  name: angular
  labels:
    app: angular
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: angular
